# Generated by Django 3.1.1 on 2020-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasisStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.TextField(default='', max_length=30)),
                ('Jaar', models.IntegerField(default=0)),
                ('Toets', models.IntegerField(default=0)),
                ('Behaald', models.BooleanField(default=False)),
            ],
        ),
    ]
