# Generated by Django 3.1.1 on 2020-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cijfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijfer', models.IntegerField(default=0)),
                ('blok', models.TextField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Toets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.TextField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.TextField(default='', max_length=10)),
                ('achternaam', models.TextField(default='', max_length=10)),
                ('cijfers', models.ManyToManyField(to='StudentOverzicht.Cijfer')),
            ],
        ),
        migrations.AddField(
            model_name='cijfer',
            name='toets',
            field=models.ManyToManyField(to='StudentOverzicht.Toets'),
        ),
    ]
