# Generated by Django 3.1.1 on 2020-09-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentOverzicht', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blok', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(default='', max_length=10)),
                ('achternaam', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Toets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toets', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cijfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijfer', models.FloatField(default=0)),
                ('blok', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok')),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.student')),
                ('toets', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets')),
            ],
        ),
        migrations.AddField(
            model_name='blok',
            name='toetsen',
            field=models.ManyToManyField(to='StudentOverzicht.Toets'),
        ),
    ]
