# Generated by Django 3.1.1 on 2020-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0002_remove_toets_toets_naam'),
    ]

    operations = [
        migrations.AddField(
            model_name='toets',
            name='toets_naam',
            field=models.CharField(default='', max_length=45),
        ),
    ]
