# Generated by Django 3.1.1 on 2020-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0002_auto_20200908_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achternaam',
            field=models.TextField(default='', max_length=10),
        ),
    ]
