# Generated by Django 3.1.1 on 2020-09-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0003_toets_toets_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='jaar',
        ),
    ]
