# Generated by Django 3.1.1 on 2020-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0004_remove_toets_jaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='toets',
            name='jaar',
            field=models.IntegerField(default=0),
        ),
    ]
