# Generated by Django 3.1.1 on 2020-09-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0005_auto_20200908_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blok', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='toets',
            old_name='naam',
            new_name='toets',
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='blok',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok'),
        ),
    ]
