# Generated by Django 3.1.1 on 2020-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0006_auto_20200924_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='blok',
        ),
        migrations.AddField(
            model_name='blok',
            name='toets',
            field=models.ManyToManyField(to='StudentOverzicht.Toets'),
        ),
    ]
