# Generated by Django 3.1.1 on 2020-09-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0007_auto_20200908_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blok',
            old_name='name',
            new_name='blok',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='voornaam',
        ),
        migrations.RenameField(
            model_name='toets',
            old_name='name',
            new_name='toets',
        ),
    ]
