# Generated by Django 3.1.1 on 2020-09-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0009_blok_toetsen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cijfers',
        ),
        migrations.AddField(
            model_name='student',
            name='cijfers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.cijfer'),
        ),
    ]
