# Generated by Django 3.1.1 on 2020-09-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0009_blok_toetsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='blok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='toets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets'),
        ),
    ]
