# Generated by Django 3.1.1 on 2020-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0010_auto_20200910_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='cijfer',
            field=models.FloatField(default=0),
        ),
    ]
