# Generated by Django 3.1.1 on 2020-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0011_auto_20200910_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achternaam',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='student',
            name='voornaam',
            field=models.CharField(default='', max_length=45),
        ),
    ]
