# Generated by Django 3.1.1 on 2020-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0011_auto_20200915_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='cijfer',
            field=models.FloatField(default=0),
        ),
    ]
