# Generated by Django 3.1.1 on 2020-09-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0012_auto_20200910_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cijfers',
        ),
        migrations.AddField(
            model_name='cijfer',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.student'),
            preserve_default=False,
        ),
    ]
