# Generated by Django 3.1.1 on 2020-09-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0012_auto_20200917_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='blok',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='toets',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets'),
        ),
    ]
