# Generated by Django 3.1.1 on 2020-09-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0013_auto_20200914_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='blok',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.student'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='toets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets'),
        ),
    ]
