# Generated by Django 3.1.1 on 2020-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0013_auto_20200917_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='cijfer',
            field=models.BooleanField(default=False),
        ),
    ]
