# Generated by Django 3.1.1 on 2020-09-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0014_auto_20200921_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cijfer',
            old_name='toets',
            new_name='voldoende',
        ),

    ]
