# Generated by Django 3.1.1 on 2020-09-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0014_auto_20200914_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cijfer',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='cijfers',
            field=models.ManyToManyField(to='StudentOverzicht.Cijfer'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='blok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.blok'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='toets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets'),
        ),
    ]
