# Generated by Django 3.1.1 on 2020-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0015_auto_20200921_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='toets',
        ),
        migrations.AddField(
            model_name='toets',
            name='toets_code',
            field=models.CharField(default='', max_length=45),
        ),
    ]
