# Generated by Django 3.1.1 on 2020-09-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0014_auto_20200917_1016'),
        ('StudentOverzicht', '0016_auto_20200921_0951'),
    ]

    operations = [
    ]
