# Generated by Django 3.1.1 on 2020-09-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0017_merge_20200921_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cijfer',
            name='cijfer',
        ),
        migrations.AddField(
            model_name='cijfer',
            name='toets_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentOverzicht.toets'),
        ),
        migrations.AlterField(
            model_name='cijfer',
            name='voldoende',
            field=models.BooleanField(default=False),
        ),
    ]
