# Generated by Django 3.1.1 on 2020-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Testpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Test',
        ),
        migrations.AddField(
            model_name='test',
            name='Behaald',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='Jaar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='Student',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='Toets',
            field=models.TextField(default=''),
        ),
    ]
