# Generated by Django 3.1.2 on 2020-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cijfer',
            name='volgorde',
            field=models.IntegerField(default=1),
        ),
    ]
