# Generated by Django 3.1.1 on 2020-09-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='toets_naam',
        ),
    ]
