# Generated by Django 3.1.3 on 2020-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20201104_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cijfer',
            name='volgorde',
            field=models.IntegerField(default=1),
        ),
    ]
