# Generated by Django 3.1.1 on 2020-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_student_student_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_nummer',
            field=models.IntegerField(default=0, max_length=61),
        ),
    ]
