# Generated by Django 3.1.2 on 2020-10-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20201029_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cijfer',
            name='datum_toets',
            field=models.DateField(default=None),
        ),
        migrations.RemoveField(
            model_name='toets',
            name='blok',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.ManyToManyField(to='Main.Blok'),
        ),
    ]
