# Generated by Django 3.1.2 on 2020-11-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20201030_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijfer',
            name='datum_toets',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.RemoveField(
            model_name='toets',
            name='blok',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Main.blok'),
        ),
    ]
