# Generated by Django 3.1.3 on 2020-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_cijfer_volgorde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cijfer',
            name='volgorde',
        ),
        migrations.AddField(
            model_name='toets',
            name='volgorde',
            field=models.IntegerField(default=1),
        ),
    ]
