# Generated by Django 3.1.2 on 2020-10-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20201002_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok',
            name='jaar',
            field=models.IntegerField(default=1),
        ),
    ]
