# Generated by Django 3.1.1 on 2020-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0005_toets_jaar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='toetsen',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.ManyToManyField(to='StudentOverzicht.Blok'),
        ),
    ]
