# Generated by Django 3.1.1 on 2020-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0007_auto_20200924_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='toets',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.ManyToManyField(to='StudentOverzicht.Blok'),
        ),
    ]
