# Generated by Django 3.1.1 on 2020-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0008_auto_20200924_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='blok',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.CharField(default='', max_length=6),
        ),
    ]
