# Generated by Django 3.1.1 on 2020-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0009_auto_20200924_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toets',
            name='blok',
        ),
        migrations.AddField(
            model_name='toets',
            name='blok',
            field=models.ManyToManyField(to='StudentOverzicht.Blok'),
        ),
    ]
