# Generated by Django 3.1.1 on 2020-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0010_auto_20200924_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cijfers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
