# Generated by Django 3.1.1 on 2020-09-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentOverzicht', '0011_student_cijfers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cijfers',
        ),
    ]
